search 7.x | search experiences blueprints phase 1 | LRDOCS-9189
liferay-search/liferay-learn pull request #4
Opened 2021-12-13 20:06 UTC by rbohl

@peerkar @lipusz More feedback is welcomed. I will go through and ask for specific feedback on areas of particular concern.
https://issues.liferay.com/browse/LRDOCS-9189

2021-12-13 20:10 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/understanding-search-blueprints.md
> +
The whole section below is new. Please review it and let me know if its on track. We should be trying to present only what Blueprints users need to understand to more effectively use Blueprints.
 @peerkar @lipusz

2021-12-13 20:12 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +
I don't know how much flux this is in, but some review of the below is probably needed at this point. 
@peerkar @lipusz

2021-12-13 20:27 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +
It appears that both Element import/export and Blueprint import/export are in master, so I guess the below question si already answered.

2021-12-13 20:28 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/understanding-search-blueprints.md
> +The main Liferay query is a `bool` query that wraps a multitude of nested queries. It consists of two main occur clauses: `must` and `filter`.
Drawing attention to my question below: can Blueprints affect the filter clause of the main boolean query?
@peerkar @lipusz

2021-12-16 13:52 UTC, lipusz commented
**Started reviewing...** :mag::nerd_face:

2021-12-16 15:55 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +
Yeah, it's depending on https://issues.liferay.com/browse/LPS-143640

2021-12-20 14:10 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/understanding-search-blueprints.md
> +| Choose whether to include clauses from Liferay's Indexers and Keyword Query Contributors | &#10004; |
_Keyword Query_ **and _Prefilter** Contributors_

2021-12-20 14:12 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/understanding-search-blueprints.md
> +The main Liferay query is a `bool` query that wraps a multitude of nested queries. It consists of two main occur clauses: `must` and `filter`.
I think we should mention the Search Insights widget here as a great tool to inspect the generated query.

2021-12-20 14:13 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +   - [Clause Contributors](#configuring-default-clauses): Further refine which clauses are included from Liferay's backend contributors.
https://issues.liferay.com/browse/LPS-143640

2021-12-20 14:14 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +1. Preview the Blueprint. Click _Preview_ and enter a search keyword.
Use the Preview sidebar to test the blueprint (perform a search).

2021-12-20 14:14 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +1. Preview the Blueprint. Click _Preview_ and enter a search keyword.
It's not a preview of the blueprint.

2021-12-20 14:14 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +
Yes

2021-12-20 14:15 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +
The export feature is pending on this follow-up PR: https://github.com/liferay-frontend/liferay-portal/pull/1756, https://issues.liferay.com/browse/LPS-141042

2021-12-20 14:16 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +Many Blueprints will require heavy use of the Query Builder to implement the desired use case. Use the Query Builder to
This sounds scary: do we really need to highlight the "heavy" usage?

2021-12-20 14:17 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +1. If any custom Elements are required, add the Custom JSON Element to the Query Builder and write the query clause you need.
Related bug with discussion on the Custom JSON Element: https://issues.liferay.com/browse/LPS-143567

2021-12-20 14:18 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +### Choosing which Liferay Assets to Search
The type selector may be moved, https://issues.liferay.com/browse/LPS-143640

2021-12-20 14:19 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +<!-- SME Question: What are the repercussions of choosing all, or none? Do I need to add information based on https://docs.google.com/document/d/1i3TI3F2ieswmyukKduDLPsYtaTUfbLAOBYQ-ru1yFDI/edit ? --
Removing all types now tells the engine to search for all types, so it's not just as what users would normally expect. We'll have to address it.

2021-12-20 14:19 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +Always save the Blueprint after editing its Searchable Types configuration.
Maybe we should make it clear at the very beginning that no changes are saved to the database unless the Save button is clicked on, even if you elements were added/removed or updated.

2021-12-20 14:20 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +<!-- possibly a confusing heading, particularly as it follows ### Choosing which Liferay Assets to Search -->
https://issues.liferay.com/browse/LPS-143640

2021-12-20 14:22 UTC, lipusz requested changes
Added some minor comments. Remember to take new screenshots from Master, especially after https://issues.liferay.com/browse/LPS-143640 will be implemented.

2021-12-20 14:22 UTC, lipusz commented
Finished reviewing. Nice job with covering the clauses section, Russ! :+1:

2021-12-20 14:23 UTC, lipusz commented
As Petter is focusing on the code changes, he may not be able to give you feedback before he goes on PTO today.

2021-12-20 14:27 UTC, rbohl commented
Thanks Tibor. What path should I take?

**Path 1:** Update this content as per Tibor's requests, make final edits, and send it forward to KM review > Write more content and get Petteri's final review separately.

**Path 2:** Update this content as per Tibor's requests > Add more articles to the PR and get Petteri's review > Get more review on new content from Tibor > Send forward to KM Review in early January.

**Path 3:** Something entirely different :space_invader:

2021-12-20 14:30 UTC, lipusz commented
I'll have a follow-up call with May Chen on https://issues.liferay.com/browse/LPS-143640 today. Let's see which direction we are going to take and decide afterwards.

You can skip asking further reviews from Petteri until he'll be back in January. We can (and will need to) make changes to the published docs later.

2021-12-20 20:49 UTC, peerkar commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +
Good point. Would nice to have a warning, something like with Web Content Structures that "This Blueprint is in use at xyz. Modifying it will ... ..." Maybe a feature request for the future @lipusz ?

2021-12-20 20:54 UTC, peerkar commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +Many Blueprints will require heavy use of the Query Builder to implement the desired use case. Use the Query Builder to
Agree with @lipusz. I'd suggest rephrasing it in a way that the "desired use case" is the driver and a possible complexity of a Blueprint is a consequence of it. Not it implies a bit the opposite.

2021-12-20 21:01 UTC, peerkar commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/understanding-search-blueprints.md
> +The main Liferay query is a `bool` query that wraps a multitude of nested queries. It consists of two main occur clauses: `must` and `filter`.
A Blueprint can completely override the main Boolean query except the permission and Publications related clauses. Those are always there.

@lipusz, Search Insights is not really bringing anything extra here if Blueprints preview is used. It has the score, explain, and the complete response string with the query.

@rbohl, please rephrase "nested queries" it refers at least to me to Nested Query type.  Even using "clauses" instead of "queries" would make a difference here.

2022-01-06 19:18 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +1. If any custom Elements are required, add the Custom JSON Element to the Query Builder and write the query clause you need.
@lipusz I can't tell what, if anything should be changed based on the JIRA ticket/discussion.

2022-01-06 19:27 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +1. If any custom Elements are required, add the Custom JSON Element to the Query Builder and write the query clause you need.
I believe I meant to refer to the fact that if you obtain the full JSON of an Element and add it into the "Custom JSON Element" box it won't work (I think you can no longer open the blueprint for editing). But if you just apply as I indicated in https://issues.liferay.com/browse/LPS-143567?focusedCommentId=2585681&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2585681, it works.

2022-01-06 19:27 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +1. If any custom Elements are required, add the Custom JSON Element to the Query Builder and write the query clause you need.
Using the Custom JSON Element requires a new article to document the schema anyway.

2022-01-06 19:34 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +1. If any custom Elements are required, add the Custom JSON Element to the Query Builder and write the query clause you need.
Okay, for now I've linked to this discussion from the description of [LRDOCS-10042](https://issues.liferay.com/browse/LRDOCS-10042), Creating Elements.

2022-01-07 14:19 UTC, lipusz commented
@rbohl Are you waiting on any input from @peerkar or we can close this one in favor a new (hopefully RC-version) of the first version of the docs?

2022-01-07 15:28 UTC, rbohl commented
I'll finish my updates today and re-send. This can be closed, though I may ask more questions in here.

2022-01-07 18:30 UTC, rbohl commented
> 



> Added some minor comments. Remember to take new screenshots from Master, especially after https://issues.liferay.com/browse/LPS-143640 will be implemented.

Created https://issues.liferay.com/browse/LRDOCS-10094

There are still some big UX changes that will need to be accounted for, in the steps and screenshots.

2022-01-07 18:33 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/creating-and-managing-search-blueprints.md
> +
Bump @lipusz :point_up:

2022-01-07 21:31 UTC, closed without merging

2022-01-07 21:31 UTC, rbohl commented
Superseded by https://github.com/liferay-search/liferay-learn/pull/5