search 7.x | search experiences blueprints phase 1 | LRDOCS-9189
liferay-search/liferay-learn pull request #7
Opened 2022-01-18 19:20 UTC by rbohl

Added some content for the article _Using Search Blueprints on a Search Page_
It needs more information, but I need feedback on what I am missing. I will leave the ticket _In Progress_ but reassign it.
@lipusz @peerkar
https://issues.liferay.com/browse/LRDOCS-9189

2022-01-18 19:24 UTC, lipusz commented
Russ: you can add Reviewers using the right sidebar so it sends us an email notif.

2022-01-18 19:24 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +
Questions :point_down:

2022-01-18 19:24 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +
Question :point_down:

2022-01-18 19:27 UTC, rbohl commented
> Russ: you can add Reviewers using the right sidebar so it sends us a different email notif.

I see; I'll try to remember that in the future :notebook:

2022-01-20 17:32 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +Also, are there details I am missing? -->
There are 2 ways to apply:
* Blueprints Options widget: select a Blueprint
* LLSO: apply a Blueprint to a page by setting 1.) the attribute `search.experiences.blueprint.id` with the ID of the your Blueprint as value to associate it with an existing Blueprint or 2.) set `search.experiences.blueprint.json` and the JSON representation of your Blueprint as value to feed it with an on-the-fly Blueprint.

2022-01-20 17:34 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +Also, are there details I am missing? -->
We should promote the usage of the Options widget for now as it offers a convenient Selector (add screenshot)

2022-01-20 17:35 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +Also, are there details I am missing? -->
Also, using LLSO requires Administrator roles, while the Blueprints Options widget (please double check!) can be permissioned to any role to edit.

2022-01-20 17:36 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +<!-- So far I haven't found a reasonable use case for this -->
Afaik, all OOTB parameters are populated correctly into the context if everything is correctly configured (like Ipstack, OpenWeatherMap) so you don't need to set anything extra, unless, you defined a custom parameter in your Blueprint.

2022-01-20 17:37 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +<!-- Should we say something about this? -->
Nope, remove.

2022-01-20 17:38 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +<!-- Should we say something about this? -->
Alternatively, you can add a note for devs that to apply a Blueprint to a search progammatically, they can set the aforementioned attributes on the `SearchContext` from the custom code.

2022-01-20 17:40 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +Also, are there details I am missing? -->
I think we should also highlight that Blueprints are applied at Search Page level: if your site has multiple pages where a Search Bar instance is present (besides or exclusively to the embedded header Search Bar instance), each page must be configured separately (through the Blueprints Options or LLSO widget) to apply a Blueprint.

2022-01-20 17:48 UTC, lipusz requested changes
See my comments.

2022-01-20 18:23 UTC, peerkar commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +<!-- So far I haven't found a reasonable use case for this -->
Yes, everything is set to go. There are primarily two scenarios when user would like to set search context attributes:

1. Testing: override OOTB search context attributes to see how Blueprint behaviour changes. There are two good candidates as examples: 1) search.experiences.ip.address to test how proximity queries behave from different public IPs and 2) search.experiences.scope.group.id to simulate results in the given group
2. Custom parameters: If user has defined/declared a custom parameter in Blueprint parameter configuration, the way to pass it is to set it in search context attributes.

2022-01-20 21:10 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +Also, are there details I am missing? -->
> Also, using LLSO requires Administrator roles, while the Blueprints Options widget (please double check!) can be permissioned to any role to edit.

Tested: Made a role, gave the role permission on LLSO and BO. Assigned a User to the Role. He can use the BO widget but gets an error about not having required permissions on the LLSO widget configuration. That sounds like it should be the expected behavior.

2022-01-20 21:11 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +Also, are there details I am missing? -->
> 

I didn't know about that second option (on-the-fly bl;ueprint by copying in the JSON to the attribute). What would be the use case for it?

2022-01-21 20:20 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.md
> +<!-- Should we say something about this? -->
Removing for now, because we'd want to show an example if we're going to mention it at all.

2022-02-03 21:48 UTC, rbohl commented
published: https://learn.liferay.com/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/using-a-search-blueprint-on-a-search-page.html

2022-02-03 21:48 UTC, closed without merging