search 7.4 | blueprints elements reference | LRDOCS-10039
liferay-search/liferay-learn pull request #9
Opened 2022-03-01 17:32 UTC by rbohl

Elements Reference Guide
https://issues.liferay.com/browse/LRDOCS-10039

2022-03-01 19:39 UTC, peerkar reviewed
Looks good! Left some quick notes there.

2022-03-01 19:39 UTC, peerkar commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +Might need an explanation of this one. The presence of a `boost: 10` throws me off here:
The score for a function score query in a nutshell is the product of query level boost and the value of contained function score query/queries. So the final score for this sample is 10 * the value from field_value_factor function. Just to mention: there are other parameters affecting the way the final score is calculated but for simplicity, we don't expose them here.

2022-03-01 19:39 UTC, peerkar commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +**Scheduling Aware:** Show only contents with a display date that's not in the future. This Element duplicates the functionality of a Liferay Search Framework query clause.
Don't know how but it would be nice if we could express, what these kind of elements ("This Element duplicates the functionality of a Liferay Search Framework query clause") are for.

They are for "build a Blueprint from scratch" scenarios (presented in previous BP version in a wizard kind of dialog when starting to create a new BP) where user disables indexer clauses and contributors (or some of them) but manually wants to restore some of the clauses created by them

2022-03-02 10:03 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +To see the JSON representation for any Element in the Query Elements screen, click the Actions icon (![Actions](../../../images/icon-actions.png)) &rarr; View Element JSON.
Note: the View Element JSON only returns the query configuration part.

2022-03-02 10:06 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +**Boost Asset Type:** Boost the given asset type. Select the Asset Type (required) from a list of registered [Assets](../../../building-applications/data-frameworks/asset-framework.md) and configure
I'd prefer to make each element to be Header 3 so they become share-able.

2022-03-02 10:07 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!-- How do I find the Asset Category ID? This is ugly to have to document. Can't we provide a user friendly dropdown list of categories, like we do for Asset Entries in the Boost Asset Type Element?
https://issues.liferay.com/browse/LPS-140641

2022-03-02 10:07 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!-- How do I find the Asset Category ID? This is ugly to have to document. Can't we provide a user friendly dropdown list of categories, like we do for Asset Entries in the Boost Asset Type Element?
You can navigate to the Categories admin and obtain it from the URL.

2022-03-02 10:11 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!-- How do I find the Asset Category ID? This is ugly to have to document. Can't we provide a user friendly dropdown list of categories, like we do for Asset Entries in the Boost Asset Type Element?
`http://localhost:8080/group/guest/~/control_panel/manage/-/categories_admin/vocabulary/42455/category/42456`

2022-03-02 10:12 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<http://localhost:8080/group/guest/~/control_panel/manage/-/categories_admin/vocabulary/41891/category/41892>
Oh, you got it. :-)

2022-03-02 10:14 UTC, lipusz requested changes
See my comments. Thank you Russ! :+1:

2022-03-02 15:37 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +Might need an explanation of this one. The presence of a `boost: 10` throws me off here:
So my example was originally

`sqrt ({factor} * {versionCount})`

but should really be 

`{boost} * (sqrt ({factor{ * {versionCount}))`

Correct?

2022-03-02 15:41 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +**Scheduling Aware:** Show only contents with a display date that's not in the future. This Element duplicates the functionality of a Liferay Search Framework query clause.
The next sentence tries to declare this very thing:

> This Element duplicates the functionality of a Liferay Search Framework query clause and is most useful for advanced use cases. For example, if you've disabled Liferay's search framework from contributing its default search clauses, you can use this Element to restore part of the lost functionality.

Is that sufficient?

2022-03-02 16:27 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!-- We messed up the title and description for these in the UI--it should be plural but it sounds like its for only one Segment. -->
@lipusz we might want/need another LPS ticket around this title and description: you can enter multiple segments but we make it sound like only one.

2022-03-02 16:28 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!-- Also, we should talk about Time Zone -->
@lipusz there's a typo in the element config UI: it says `Morning = 4AM - 12AM`

Also, what should I say about time zone here? Anything?

2022-03-02 16:30 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!--We should talk about how this works when the Search Bar's Search Everything setting is configured-->
@peerkar @lipusz is there something we should say about the corresponding search bar configuration "Search Everything"?

2022-03-02 16:34 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!-- We messed up the title and description for these in the UI--it should be plural but it sounds like its for only one Segment. -->
We already have these:
* https://issues.liferay.com/browse/LPS-148443
* https://issues.liferay.com/browse/LPS-147328

2022-03-02 16:35 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!-- Also, we should talk about Time Zone -->
Create a Task for the typo.

>Also, what should I say about time zone here? Anything?

I guess everything will be in the server's time. :thinking: @peerkar can probably share more.

2022-03-02 16:36 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!--We should talk about how this works when the Search Bar's Search Everything setting is configured-->
We can just say that it kinda does the same thing as the mentioned Search Bar config.

2022-03-02 17:07 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!-- We messed up the title and description for these in the UI--it should be plural but it sounds like its for only one Segment. -->
https://issues.liferay.com/browse/LPS-148462

2022-03-02 17:09 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!-- Also, we should talk about Time Zone -->
https://issues.liferay.com/browse/LPS-148463

2022-03-02 17:15 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +<!--We should talk about how this works when the Search Bar's Search Everything setting is configured-->
Okay, so it overlaps with the Scope: This Site configuration. I can mention that.

2022-03-02 17:16 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +**Limit Search to These Sites:** Limit the search scope to the given sites. Filter results using a Terms query on the `scopeGroupId` field, matching its value with the configured Group IDs.
@peerkar @lipusz, similar to my above comment on Limit Search to the Current Site, I'll add a mention of the Search Bar's Scope configuration. I wonder: Must the user set the scope to Everything for this Element to work on the search page?

2022-03-02 17:20 UTC, lipusz commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +**Limit Search to These Sites:** Limit the search scope to the given sites. Filter results using a Terms query on the `scopeGroupId` field, matching its value with the configured Group IDs.
I believe this element is really just a convenient to limit the scope, in the Preview. The Search Bar's groupIds will always win over the element's if I'm not mistaken. :thinking:

2022-03-02 19:19 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +**Limit Search to These Sites:** Limit the search scope to the given sites. Filter results using a Terms query on the `scopeGroupId` field, matching its value with the configured Group IDs.
Hmm, I assumed it was like this [Custom Filter example](https://learn.liferay.com/dxp/latest/en/using-search/search-pages-and-widgets/search-results/custom-filter-examples.html#filtering-by-site-id) where you must choose Everything in order to filter by site ID.

2022-03-02 19:31 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +**Limit Search to These Sites:** Limit the search scope to the given sites. Filter results using a Terms query on the `scopeGroupId` field, matching its value with the configured Group IDs.
Tested--it works on a search page if you choose the Everything scope (doesn't work if you choose This Site).

2022-03-02 19:34 UTC, rbohl commented on docs/dxp/latest/en/using-search/liferay-enterprise-search/search-experiences/search-blueprints-elements-reference.md
> +**Limit Search to These Sites:** Limit the search scope to the given sites. Filter results using a Terms query on the `scopeGroupId` field, matching its value with the configured Group IDs.
I propose to add this: > This Element's functionality overlaps with the [Search Bar's](../../getting-started/searching-for-content.md#configuring-the-search-bar) Scope configuration option. You must set the scope to _Everything_.

2022-03-02 21:44 UTC, rbohl commented
Forwarded here with the suggested edits: https://github.com/jrhoun/liferay-learn/pull/1400

However, please feel free to add last minute comments @peerkar and @lipusz

2022-03-04 11:39 UTC, closed without merging